name: CI

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]
  workflow_call:
    inputs:
      skip-pr-comments:
        description: 'Skip PR comments (useful for releases)'
        required: false
        type: boolean
        default: false
    outputs:
      coverage:
        description: 'Coverage percentage'
        value: ${{ jobs.main-ci.outputs.coverage }}

jobs:
  main-ci:
    name: Lint, Type Check, Test, and Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: ${{ github.event_name == 'pull_request' && 'write' || 'none' }}
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node environment
        uses: ./.github/actions/setup-node-env

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Check Prettier formatting
        run: npx prettier --check "src/**/*.{ts,js}"

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Generate coverage report
        if: ${{ !inputs.skip-pr-comments && github.event_name == 'pull_request' }}
        uses: ./.github/actions/coverage-report
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -f "dist/simple-inventory-card.js" ]; then
            echo "Build output not found!"
            exit 1
          fi
          echo "Build successful - output size: $(wc -c < dist/simple-inventory-card.js) bytes"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7
